FROM python:3.12-slim

WORKDIR /code

COPY ./requirements.txt ./

RUN pip install --no-cache-dir --timeout=1000 --verbose -r requirements.txt

COPY ./src ./src
#COPY ./.env ./.env

EXPOSE 8051

CMD ["python", "src/server.py"]